services:
  - type: web
    name: train-track-backend
    env: python
    pythonVersion: 3.10
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: shuttle.proxy.rlwy.net
      - key: DB_PORT
        value: "59084"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: ejFywNNFCowuXALqixQkPJjzFpyIVoTN
      - key: DB_NAME
        value: railway
      - key: FLASK_SECRET_KEY
        value: prod_secret_key
